#!/bin/bash
#---------------Script SBATCH - NLHPC ----------------
#SBATCH -J metgrid
#SBATCH -p general
#SBATCH -n 1
#SBATCH -c 1
#SBATCH --mem-per-cpu=4000
#SBATCH --mail-user=correo@dgac.gob.cl
#SBATCH --mail-type=ALL
#SBATCH -t 00:15:00
#SBATCH -o logs/geogrid_%j.out
#SBATCH -e logs/geogrid_%j.err

#-----------------Toolchain---------------------------
cd /home/courses/studentXX/models/wps/WPS-4.2/

ml purge
ml intel/2022.00

# -----------------Modulos----------------------------
ml WPS/4.2-dmpar

# ----------------Comando-----------------------------
srun ./metgrid.exe
